### ISSUE TITLE
similarity encoder broken by recent change in scikit-learn _BaseEncoder

### ISSUE THREAD

**Issue by jeromedockes** [dirty-cat/dirty_cat#103]
_BaseEncoder._check_X now returns X_columns, n_samples, n_features
(from git blame:

b2344a4e3f7924d92ff02b6e9dc476919da606da (maikia                2019-03-01 11:02:57 +0100  70)         return X_columns, n_samples, n_features

)

**Comment by willettk** [comment]
Echoed that this breaks on the current version of scikit-learn. I'm able to run the [example script](https://dirty-cat.github.io/stable/auto_examples/02_fit_predict_plot_employee_salaries.html#sphx-glr-download-auto-examples-02-fit-predict-plot-employee-salaries-py) using scikit-learn 0.20.2, but fitting a pipeline with the SimilarityEncoder() returns an error when using scikit-learn 0.21.1. 

This means that most of the example scripts will currently only work for one minor version, since ColumnTransformer() (which is used in almost all examples) was only introduced in 0.20.0.

**Comment by amueller** [comment]
@willettk "minor" is the only kind of version there is for sklearn - apart from bug-fix ;)

**Comment by GaelVaroquaux** [comment]
This is fixed, I believe. Closing.
