### ISSUE TITLE
Travis is gone

### ISSUE THREAD

**Issue by GaelVaroquaux** [dirty-cat/dirty_cat#113]
We need to find out why travis is gone.

**Comment by alexis-cvetkov** [comment]
The problem is that Travis cannot use the command `codecov` to measure the code coverage of the tests. Usually this package is installed with conda as defined in the .travis.yml file, but it is not the case anymore. When looking at https://travis-ci.org/github/dirty-cat/dirty_cat/builds/637915880 (line to 868 to 976), it seems that the coverage package is pinned to version <5, which prevent codecov from being installed.

![image](https://user-images.githubusercontent.com/33491786/79207172-a6394800-7e40-11ea-93b6-93fba3bf272b.png)

I don't know how pinned specs are handled, for now a quick fix is to manually install codecov with `pip install codecov` in .travis.yml (see PR #109)

**Comment by GaelVaroquaux** [comment]
But it seems to me that Travis is not even run

**Comment by alexis-cvetkov** [comment]
Yes, for some reason travis wasn't returning any error message on github. It's only on https://travis-ci.org/github/dirty-cat/dirty_cat that I was able to see that the build failed due to codecov. After modifying .travis.yml to install codecov manually, Travis notifications started to appear again on github.

**Comment by GaelVaroquaux** [comment]
Excellent job!!!!

**Comment by alexis-cvetkov** [comment]
After some digging, it appears that the 5.0 release of the `coverage` package broke some tests in astropy (https://github.com/astropy/astropy/issues/9792). For now they decided to pin the version of `coverage<5` in astropy/ci-helpers (https://github.com/astropy/ci-helpers/pull/432).
When running Travis, coverage 5.0 is installed as a dependency of `pytest-cov` and `codecov`. Because of the pinning it is downgraded to 4.5.4, which entails the removing of codecov.
