### ISSUE TITLE
Codecov for ``count_3_grams.py`` at 0%

### ISSUE THREAD

**Issue by LilianBoulard** [dirty-cat/dirty_cat#149]
Hi,

On the [codecov report](https://codecov.io/gh/dirty-cat/dirty_cat/tree/master/dirty_cat), I can see that it considers the file ``count_3_grams.py`` as not tested (coverage at 0%).

However, when we take a peak into the file, we can see there are actually test units inside.
\
It is also said in the docstring:
> Run unit tests with "pytest count_3_grams.py"

In order for the code coverage to improve, I would advise splitting the file in two so that the test units move into ``dirty_cat/tests/``.

Please tell me if it's fine to do that, and I'll submit a PR.

Thanks
Lilian

**Comment by Phaide** [comment]
I checked the tests, see if they succeeded, but the answer is no:
![Screenshot from 2020-10-28 15-47-42](https://user-images.githubusercontent.com/33222654/97452436-0901b500-1935-11eb-9160-dad90235c95c.png)

What should we do ?

Thanks
Lilian

**Comment by amy12xx** [comment]
It looks like this was done for experimentation/benchmarking, and is not being referenced in the code. I don't know if it it worth it to fix the tests, and move to under tests/ since that will also increase the test run time.

One option may be to move this to a different folder that can be ignored by codecov. 

I'll let @GaelVaroquaux weigh in.
