### ISSUE TITLE
GapEncoder - RuntimeWarning: overflow encountered in reciprocal , overflow encountered in true_divide

### ISSUE THREAD

**Issue by krumeto** [dirty-cat/dirty_cat#160]
Dear Team,

I am working on a roughly 4 mil rows dataset with 9 categorical features, having from 35 to 5300 unique values. I am trying to use GapEncoder, due to the combination of size and cardinality. 

When trying to encode the full dataset, I keep running into the **RuntimeWarnings** below:
```
/home/cdsw/.local/lib/python3.6/site-packages/dirty_cat/gap_encoder.py:558: RuntimeWarning: overflow encountered in reciprocal
  A += W * safe_sparse_dot(Ht.T, Vt.multiply(np.dot(Ht, W) ** -1))
/home/cdsw/.local/lib/python3.6/site-packages/dirty_cat/gap_encoder.py:600: RuntimeWarning: overflow encountered in true_divide
  aux = np.dot(W_WT1_, vt_ / np.dot(ht, W_))
/home/cdsw/.local/lib/python3.6/site-packages/dirty_cat/gap_encoder.py:601: RuntimeWarning: invalid value encountered in multiply
  ht_out = ht * aux + const
```
I have tried initializing with 'random' and using hashing, but keep running into the same. 
When trying to encode column by column, I cannot find a clear pattern - the overflow happens for columns with low cardinality, as well as for such with high ones. At the same time, some columns are encoded successfully.

An example of a column that runs into the Warning:

[Mercy Medical Center (Des Moines, IA), Mercy Medical Center (Roseburg, OR), Harrison Medical Center (Bremerton, WA), St. Joseph Hospital East (Lexington, KY), Lakeside Hospital (Omaha, NE), ..., Plainview Hospital (Plainview, NE), Continuing Care Hospital (Lexington, KY), Regional Hospital for Resp (Seattle, WA), Creighton University Medical Center (Omaha, NE), St. Alexius Garrison Family Clinic (Garrison, ND)]

Python 3.6.8, [GCC 5.4.0 20160609] on Cloudera Workbench (Linux)
sklearn version = '0.23.1'
scipy version = '1.5.0'
numpy version = '1.18.5'
pandas version = '1.0.4'

**Any advice or direction would be more than welcome! Please let me know if you need anything else.**

**Comment by alexis-cvetkov** [comment]
Hello @krumeto

Thank you for raising this issue! I think the **RuntimeWarnings** you get are due to the quantity `np.dot(Ht, W)` having very small values (< 5e-324), thus raising overflow errors when the algorithm computes the element-wise inverse of this quantity (as in `np.dot(Ht, W) ** -1`).

To show that, I trained the GapEncoder on a random array of strings with length = 1M and various cardinalities (10k, 20k, 100k). I plot below the evolution of the minimum value of `np.dot(Ht, W)` as the training goes.

![image](https://user-images.githubusercontent.com/33491786/108849176-29d7cf80-75e2-11eb-8eaf-15877cdb44ef.png)

We can see that `np.dot(Ht, W)` takes smaller and smaller values as the training goes (mostly due to `W` being too small), but I was only able to see this when the cardinality is high. I guess it can also happen with low cardinality, as in your case, but may depend on the data.

For now a quick fix would be to prevent `W`  from taking arbitrarily small values. This can be done by thresholding values that are too small after training on each batch (see code below). From quick experiments it doesn't seem to change the encodings a lot, except for a few coefficients, but I am going to check if this is a proper way of tackling this issue in the future.

```
batches = np.array_split(X, len(X)//128) # Split your data X in batches of size 128.
enc = GapEncoder()
for batch in batches:
    enc.partial_fit(batch)
    enc.W_[enc.W_ < 1e-20] = 1e-20 # Prevent W from having values smaller than 1e-20
```

**Comment by krumeto** [comment]
Hi @alexis-cvetkov and thanks a lot!,

We will run experiments on our dataset vs. SimilarityEncoder and can post metrics results afterwards. 

To add to the above, can you please confirm if Gapencoder expects a single column as an input?

When we try to fit it on multiple columns, we get:
`AssertionError: ERROR:        shape (4024877, 2) of input array is not supported`

We thus create a step per column in the ColumnTransformers we use.

Thank you in advance again,
Krum

**Comment by alexis-cvetkov** [comment]
Yes for now the GapEncoder works for a single column only, so you have to train one model for each column.
A comparison with SimilarityEncoder would be greatly appreciated indeed ! Note that you can also use the MinHashEncoder which should be quite fast.

**Comment by GaelVaroquaux** [comment]
> (as in np.dot(Ht, W) ** -1).

To avoid underflows, we should probably write this as

1. / (np.dot(Ht, W) + 1e-10))

Can you test that it fixes the problem and we'll update the library.

Do we have a test case that we can use to reproduce and build a unit
test.

**Comment by krumeto** [comment]
@alexis-cvetkov If it would help for reproducing, the column on which I am testing is the following one:

Total values are 4391599, total unique values are 59. 

Example of values (we can do some preprocessing to go around it for sure):
`[Mercy Medical Center (Des Moines, IA), Mercy Medical Center (Roseburg, OR), Harrison Medical Center (Bremerton, WA), St. Joseph Hospital East (Lexington, KY), Lakeside Hospital (Omaha, NE), ..., Plainview Hospital (Plainview, NE), Continuing Care Hospital (Lexington, KY), Regional Hospital for Resp (Seattle, WA), Creighton University Medical Center (Omaha, NE), St. Alexius Garrison Family Clinic (Garrison, ND)]`

I tried tracking the minimum W throughout batches - it gets really small really fast:
![image](https://user-images.githubusercontent.com/11272436/108897599-f23b4880-761e-11eb-8c35-dd76ea36d3b3.png)

Interestingly, when we used .partial_fit(batch), we did not get the error message. Just when we tried fitting all at once.

**Comment by alexis-cvetkov** [comment]
Thanks you for the details @krumeto. I have been able to reproduce this issue on a simple example which is quite fast to run:
```
import numpy as np
import matplotlib.pyplot as plt
from dirty_cat import GapEncoder

np.random.seed(0)
X = np.random.randint(1e5, 1e6, size=(8000, 1)).astype(str)

enc = GapEncoder(random_state=0, n_components=2, batch_size=1,
                 min_iter=1, max_iter=1)
enc.fit(X)
```
This example raises the same RuntimeWarnings that you got, and Gael's suggestion fixes it.
I have opened the PR #161 with the fix and a unit test.

> Interestingly, when we used .partial_fit(batch), we did not get the error message. Just when we tried fitting all at once.
Yes I realized my example doesn't raise any error with `partial_fit` too. I am not 100% sure why but I noticed that `np.dot(Ht, W)` decreases faster when the number of unique n-grams in the data is high (which I think is why you can get this error even with low cardinality data). This happens more when using `fit` rather than `partial_fit` because in the first case the matrix of n-grams counts that we want to factorize is built from all the data (which has a lot of n-grams). With `partial_fit` the number of different n-grams increases slowly with each batch, hence a slower decrease. This is coherent with what I observe in my toy example (slower decrease with partial fit and no error raised).
