### ISSUE TITLE
Deduplication

### ISSUE THREAD

**Issue by LilianBoulard** [dirty-cat/dirty_cat#306]
As discussed with Gaël and Jovan, we could get some inspiration from the [dedupe library](https://github.com/dedupeio/dedupe) for the fuzzy join and deduplication features.

**Comment by mjboos** [comment]
Summary of my current understanding of the different approaches one could take to this:

### Dedupe
Dedupe allows deduplication based on multiple fields and (simplifying a bit) computes a string similarity (levenshtein AFAICT) between fields for each pair of records. It then performs hierarchical clustering on the similarities between records to identify duplicates. There are three tricks/fancy things it uses on top of that:
- It scales this by pre-selecting blocks of data to compare with each other based on (more computationally efficient) "predicate functions", e.g. only do full string comparison of records if they share the first three digits (+ many more predicate functions and combinations thereof), see [here](https://docs.dedupe.io/en/latest/how-it-works/Making-smart-comparisons.html#).
- It computes a string similarity between two records for each field independently, i.e. 5 fields lead to 5 string similarities (between two records). Since not all fields are equally informative, it uses a logistic regression with similarity per field as features to predict whether something is a duplicate (and hence be able to down-weight certain fields via logistic reg. weights). It learns them via presenting the most uncertain examples to the user and collecting ground truth about whether they are duplicates from them.
- It selects the cut-off for hierarchical clustering by precision/recall based on the ground truth data collected from the user via the active inference above.

Disadvantage is clearly the complexity and maybe the reliance on user input, yet using logistic regression or similar for weighting different fields seems very useful.

### Simplest alternative using native dirty_cat and scipy

[This](https://mjboos.github.io/posts/2021/11/unsupervised-typo-finder/) example uses a similar principle, but much simplified using only dirty_cat and scipy clustering: For a single field compute similarities via `SimilarityEncoder`, then perform hierarchical clustering on this and let the user pick the cut-off. Basically the approach that dedupe takes using dirty_cat's string similarities without the fancy things above. It would struggle with scaling (always performs an all-to-all string similarity), doesn't have a principled way to do similarity across 2+ fields/columns jointly, and has no heuristic to pick the cut-off.

### Building on FuzzyJoin

It would be nice to build this on the fuzzyjoin PR, since this already handles matching on multiple columns - but we might want to have better string similarity than n-gram CountVectorizer and for clustering (and potentially weighting columns differently) we might need user input/ground truth labels.

### Open questions

IMO the biggest ones are:

1. How much do we care about the ability to scale this to large datasets? Depending on this we might need to use a similar "block comparisons only" strategy that dedupe uses.
2. Do you want to have a dirty_cat user experience that requires input by users, i.e. to get ground truth labels of duplicates?

It also would be interesting to allow generic similarities, e.g. using something like similarity in a gapencoder-derived vector space could be interesting.

@GaelVaroquaux @LilianBoulard

**Comment by mjboos** [comment]
After quick discussion with Gael, the plan looks like:

1. Deduplicate function that accepts a single field/column, computes similarity between records via FuzzyJoin-like CountVectorizer, does hierarchical clustering and returns cluster assignments. Hyperparameter would be the `fcluster` cutoff. Maybe accept simple user input (whether there aren't any matches).
2. Scale up via Min Hashing and/or comparing only inside blocks (dedupe-style).
3. Extend to similarity between records based on multiple fields.
4. Accept more user input to learn a distance function (simplest idea: for weighting different fields/columns).
