### ISSUE TITLE
Location of data download

### ISSUE THREAD

**Issue by GaelVaroquaux** [dirty-cat/dirty_cat#35]
Currently the data are downloaded in the source directory of dirty cat. This is not a good solution, because dirty cat might be installed as root and hence this directory not writable. We need to use something either in the home dir or in the local dir.

**Comment by pierreglaser** [comment]
we can create a more hierarchical decision process in the `dataset.get_data_dir()` function.
In nilearn, the order of priority is as follows:

>     1. defaults system paths
>     2. the keyword argument data_dir
>     3. the global environment variable DIRTYCAT_SHARED_DATA
>     4. the user environment variable DIRTYCAT_DATA
>     5. dirty_cat_data in the user home 

Since we are in an early stage, the simplest solution that still offers modularity would be to keep steps 2 and 5. 3 and 4 won't hurt much though. 
Thoughts?

**Comment by GaelVaroquaux** [comment]
Agreed with all this.

**Comment by GaelVaroquaux** [comment]
This has been fixed.
