### ISSUE TITLE
Fetching functions' style is not great

### ISSUE THREAD

**Issue by LilianBoulard** [dirty-cat/dirty_cat#357]
![image](https://user-images.githubusercontent.com/33222654/190182237-17b1a4c5-a0fb-404d-8af8-05fdf30f8d79.png)

Two issue I notice:
- The title is overlapping with the logo (linked to #349)
- The quote doesn't work
- There is no link to `DatasetInfoOnly` and `DatasetAll` (linked to #330)

**Comment by GaelVaroquaux** [comment]
Does this PR fixes the problem of the link to DatasetAll? I don't see it on the generated docs https://output.circle-artifacts.com/output/job/3b7bea98-86da-49ee-91bd-fdc9f0eefc58/artifacts/0/doc/generated/dirty_cat.datasets.fetch_midwest_survey.html#dirty_cat.datasets.fetch_midwest_survey

Actually, I think that understand what's going on: the object DatsetAll (and DatasetInfoOnly ) are not documented anywhere in the documentation. We should add an rst file that contains their documentation (as eg for the encoders and functions that are documented in the index.rst). I don't want to add them to the index.rst because they are somewhat technical details that we should not advertise on the front page. I think that we can add a dedicated documentation page to them, and that we do not even have to worry about linking this page anywhere in particular.
